dist: xenial
language: python
python:
  - "3.6"
  - "3.7"
# Install dependencies
before_install:
  - python --version
  - uname -a
install:
  - pip install flake8==3.7.8
  - pip install pytest==4.4.1
  - pip install pytest-cov==2.6.1
  - pip install -r requirements.txt
  - pip freeze
# Execute the tests and the linter
script:
  - pytest --cov=pyqtt_application
  - flake8 --ignore=E501,W503,E203
  - echo "Done"